Balance_management/urls.py
from django.urls import path
from . import views

app_name = "Balance_Management"
urlpatterns = [
    path('index', views.index, name='index_bm'),
    path('SelectProfile', views.SelectProfile.as_view(), name="SelectProfile"),
    # Supply when select user at create profile page
    path('SelectProfile_API', views.SelectProfile_API.as_view(), name="SelectProfile_API"),
    # path('confirm_useable_profilename', views.select_user, name='confirm_useable_profilename'),
    # path('select_user1', views.select_user, name='select_user1'),
    ]

NHSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('main.urls')),
    path(r'Balance-management/', include('Balance_management.urls')),
    path(r'login/', auth_views.LoginView.as_view(template_name='Login.html'), name='login'),
    path(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(r'signup/', views.signup, name='signup'),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index_main'),
    ]

Balance_management/models.py
from django.db import models

# Create your models here.

Balance_management/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse


# Create your views here.
def index(request):
    context = {}
    # 表示するアプリ集
    if not "Balance-Management_Profile" in request.session:
        return redirect("SelectProfile")
    
    return render(request, "Balance-Management/index.html", context)

class SelectProfile(View):
    def get(self, request):
        context = {}
        context["Profile"] = [
            {"id" : "000111222333", "name":"Profile_Test1"},
            {"id" : "111222333444", "name":"Profile_Test2"},
            ]
        context["UserList"] = [
            {"id":"0070200366", "name":"UserA"},
            {"id":"0070200367", "name":"UserB"},
            {"id":"0070200368", "name":"UserC"},
        ]
        request.session["Balance-Management_Profile"] = "Test"
        return render(request, "Balance-Management/Select_Profile.html", context)
class SelectProfile_API(View):
    def post(self, request):
        API_type = request.POST["type"]
        if API_type == "get_user":
            json = self.select_user(request)
        elif API_type == "confirm_name":
            json = self.confirm_useable_profilename(request)
        return JsonResponse(json)
    def select_user(self, request) -> list:
        user1 = request.POST['user1']
        # check record exists
        if user1 in []:
            pass
        user2 = {
            "0070200366":{"id":"0070200366", "name":"UserA"},
            "0070200367":{"id":"0070200367", "name":"UserB"},
            "0070200368":{"id":"0070200368", "name":"UserC"},
        }
        del user2[user1]
        user2 = list(user2.values())
        # if user1 == "UserA":
        #     user2 = [
        #         {"id":"0070200367", "name":"UserB"},
        #         {"id":"0070200368", "name":"UserC"},
                
        #         ]
        # else:
        #     user2 = [
        #         {"id":"0070200366", "name":"UserA"},
        #         {"id":"0070200368", "name":"UserC"},
                
        #         ]
        # return other user
        d = {
            "User2": user2
        }
        return d
    def confirm_useable_profilename(self, request) -> bool:
        profile_name = request.POST["name_profile"]
        # if inputted profile name already exists at db, return false because duplicate is not supported
        if profile_name in ["Used_Test"]:
            d = {
                "judge": False
            }
            return d
        else:
            d = {
                "judge": True
            }
            return d

templates/Balance-Management/Layout1_HasLeftIcon.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Here input the title{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'Balance-Management/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'Balance-Management/css/Layout1.css' %}">
    <script src="{% static 'javascript/jquery-3.6.0.js' %}"></script>
    {% block css %}{% endblock %}
</head>
<body>
    
    <div class="LeftWrap">
        <div class="IconImg">

            <img src="{% static 'Balance-Management/img/icon_left_inst.png' %}" alt="icon">
            <span class="AppVersion">Ver1.0</span>
            <span class="AppName">Balance<br>Management</span>
        </div>
        
    </div>
    <div class="Wrap_Main">
        {% block bodywrap %}
        {% endblock %}
    </div>
    {% block javascript %}
    {% endblock %}
</body>
</html>

templates/Balance-Management/Layout2_Home_HasAppName.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Here input the title</title>
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/Layout2.css">
</head>
<body>
    <div class="HeadWrap">
        <div class="Menu">

            <a href="" class="Head_Button">
                Home
            </a>
            <a href="" class="Head_Button">
                Input
            </a>
            <a href="" class="Head_Button">
                History
            </a>
            <a href="" class="Head_Button">
                Report
            </a>
            <a href="" class="Head_Button">
                Master
            </a>
        </div>
        <div class="Profile">
            <ul>
                <li>
                    User:svc5brid
                </li>
                <li>
                    Profile:Test_Main
                </li>
            </ul>
        </div>
        
        <!-- クリックするとユーザー、プロファイルが表示される的な
        <div class="Profile">

        </div> -->
    </div>
    <div class="BodyWrap">
        <div class="LeftWrap">
        <span class="AppName">
            Balance<br>Management
        </span>
        <div class="VersionWrap">
            <span class="AppVersion">
                Ver1.0
            </span>
        </div>
        </div>
        <div class="Wrap_Main">
            Content Area
        </div>
    </div>
    <div class="FootWrap">
        <span class="Copyright">
            Copyright © 2022 svc5brid All Rights Reserved.
        </span>
    </div>
</body>
</html>

templates/Balance-Management/Layout2_Home_NoneAppName.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Here input the title</title>
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/Layout2.css">
</head>
<body>
    <div class="HeadWrap">
            
        <span class="AppName_Little">
            Balance<br>Management
        </span>
        <div class="Menu">
            <a href="" class="Head_Button">
                Home
            </a>
            <a href="" class="Head_Button">
                Input
            </a>
            <a href="" class="Head_Button">
                History
            </a>
            <a href="" class="Head_Button">
                Report
            </a>
            <a href="" class="Head_Button">
                Master
            </a>
        </div>
        <div class="Profile">
            <ul>
                <li>
                    User:svc5brid
                </li>
                <li>
                    Profile:Test_Main
                </li>
            </ul>
        </div>
        
        <!-- クリックするとユーザー、プロファイルが表示される的な
        <div class="Profile">

        </div> -->
    </div>
    <div class="BodyWrap">
        <div class="LeftWrap">
    
        </div>
        <div class="Wrap_Main">
            Content Area
        </div>
    </div>
    <div class="FootWrap">
        <span class="Copyright">
            Copyright © 2022 svc5brid All Rights Reserved.
        </span>
    </div>
</body>
</html>

templates/Balance-Management/Select_Profile.html
<!-- 必須 -->
{% extends 'Balance-Management/Layout1_HasLeftIcon.html' %}
{% load static %}
<!-- head内のタイトル -->
{% block title %}
Select Profile
{% endblock %}
<!-- 固有のcssがあれば記載 -->
{% block css %}
<!-- <link rel="stylesheet" href="{% static 'css/AboutUs.css' %}"> -->

{% endblock %}
<!-- ボディー部分 -->
{% block bodywrap %}
    <h1>
        Select Profile here
    </h1>
    <select name="" id="">
        {% for i in Profile %}
        
        <option value="{{i.id}}">{{i.name}}</option>
        {% endfor %}
    </select>
    <button>
        Go
    </button>
    <h1>
        Create New Profile here
    </h1>
    <label for="">
        Profile Name
        <input type="text" id="Form_Create_Name">
    </label>
    <span id="name_useable">

    </span>
    <label for="">
        Choice User 1
        <select name="" id="Form_Create_User1">
            <option disabled selected>select user2</option>
            {% for i in UserList %}
        
            <option value="{{i.id}}">{{i.name}}</option>
            {% endfor %}
        </select>
    </label>
    <label for="">
        Choice User 2
        <select name="" id="Form_Create_User2" disabled>
            <option disabled selected>select user2</option>
        </select>
    </label>
    <button>
        Create
    </button>
    
{% endblock %}
<!-- javascriptがあれば記載。 -->
{% block javascript %}
<script>
    //csrf_token
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    
    var csrftoken = getCookie('csrftoken');
    
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    
    //Confirm useable of inputted profile name
    $('#Form_Create_Name').change(function(e){
        //execute only inputted anything
        if($("#Form_Create_Name").val()!=""){
            //リクエストの設定
            $.ajax({
                //urlが送信先
                'url': '{% url "Balance_Management:SelectProfile_API" %}',
                //typeはgetなのかpostなのか。
                'type': 'POST',
                //サーバーに送信するデータ。
                'data': {
                    'type': "confirm_name",
                    'name_profile': $('#Form_Create_Name').val(),
                },
                //上のデータ形式。
                'dataType': 'json'
            })
            .done(function(response){
                const judge = response.judge;
                $("#name_useable").html(judge);
                console.log(judge)
            });
        }else{
            $("#name_useable").html("");
        }
    })

    //送信のところ。submitを検知する。
    $('#Form_Create_User1').change(function(e){
        //送信を止める
        e.preventDefault();
        //リクエストの設定
        $.ajax({
            //urlが送信先
            'url': '{% url "Balance_Management:SelectProfile_API" %}',
            //typeはgetなのかpostなのか。
            'type': 'POST',
            //サーバーに送信するデータ。
            'data': {
                'type': "get_user",
                'user1': $('#Form_Create_User1').val(),
            },
            //上のデータ形式。
            'dataType': 'json'
        })
        .done(function(response){
            const a = response.User2;
            const select = document.getElementById("Form_Create_User2")
            if (select.hasChildNodes()) {
                while (select.childNodes.length > 0) {
                    select.removeChild(select.firstChild)
                }
            }
            const option = document.createElement('option');
            option.disabled = true;
            option.innerHTML = "select user2"
            option.selected = true
            select.appendChild(option)
            a.forEach((value, index) => {
                const option = document.createElement('option');
                option.value = value.id;
                option.innerHTML = value.name;
                select.appendChild(option);
            })
            select.disabled = false;
        });
    })
</script>

{% endblock %}

templates/Balance-Management/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

</body>
</html>